### ISSUE TITLE
What could be the issue

### ISSUE THREAD

**Issue by Arise** [Petschko/Java-RPG-Maker-MV-Decrypter#1]
```
java.lang.NullPointerException:` Decryption-Code is not set!
        at org.petschko.rpgmakermv.decrypt.Decrypter.decryptFile(Decrypter.java:217)
        at org.petschko.rpgmakermv.decrypt.GUI$GUI_Decryption.doInBackground(GUI.java:359)
        at org.petschko.rpgmakermv.decrypt.GUI$GUI_Decryption.doInBackground(GUI.java:275)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Petschko** [comment]
Can you please tell me, what you've done before the error occoured?

"Decryption-Code is not set!" - Means that there is no Decryption-Key (Found?), but it should not crash so please tell me your steps to reproduce that =)

**Comment by Arise** [comment]
Is not crashing, for every file in the folder it just throws the error. I see it in the console. In the output folder I find just the encrypted files.

**Comment by Arise** [comment]
Ok, figured out, it seems the game is using some other technique to encrypt the game data to protect the System.json file. After I decrypted the System.json and placing it in the folder your tool worked properly.
Thanks!

**Comment by Petschko** [comment]
Ah okay, glad you figured out on your own =) But thanks for reporting anyway

**Comment by Petschko** [comment]
I will show a Message if the Decryption-Key was not found, so that it is less confusing - I will implement that! (Try it on my own, it just try to Decrypt no matter if the Key is missing or not...)

**Comment by Petschko** [comment]
Is added to the next Version. It also handles non-read access on the Decryption-Key-File

See: https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/commit/b11f259b478950af8e5fd908fde346686eb5331e
