### ISSUE TITLE
crash on java 10?

### ISSUE THREAD

**Issue by xpirad** [Petschko/Java-RPG-Maker-MV-Decrypter#18]
Hi again XD. Sorry to bother you again, so I'm using windows 10 and oracle jdk 10.
when i select project folder, the project won't load and this is the console output. 

Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: sun/dc/path/PathException
        at org.petschko.rpgmakermv.decrypt.GUI.openRPGProject(GUI.java:226)
        at org.petschko.rpgmakermv.decrypt.GUI.lambda$assignMainMenuListener$0(GUI.java:162)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
        at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: sun.dc.path.PathException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 40 more

Anyway to solve this other than downgrade my jdk version? Thanks!

**Comment by RedAISkye** [comment]
Issue was already stated here with a work around.
https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/issues/16

**Comment by Petschko** [comment]
I recommend install Java 8 again, since Java 10 is just supported until Sept. 2018

![Java-Version-Support roadmap](https://jaxenter.com/wp-content/uploads/2018/03/Screen-Shot-2018-03-27-at-11.40.47-AM.png)

**Comment by xpirad** [comment]
Okay,i see.
Thanks for help!

**Comment by xpirad** [comment]
Hi @Petschko, do you have plans for supporting java 11?
It's a lts release.

**Comment by Petschko** [comment]
@xpirad yes I will look into this, probably rewrite the whole code with all my new experiences

Or I will may choose a different language since java is not that much used anymore today

**Comment by Petschko** [comment]
@xpirad since it looks like this issue here was also caused by "Oracle" classes, can you let me know if the test version in this issue https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/issues/20 works on Java11?

**Comment by xpirad** [comment]
Hi Petschko!
Thanks for updating!
I've tried 0.1.3.2, there's seems to be some connection error? I'm using the latest jdk 11.0.3
![image](https://user-images.githubusercontent.com/24430064/57195902-129d9d00-6f8a-11e9-908c-609e2903c6f6.png)

I currently don't have any rpg mv project to test, but will do so when i have.
Thanks again!

**Comment by Petschko** [comment]
Haha that's because I currently build in an Updater^^ Forgot to remove that code from starting the Program... It tries to connect to `http://localhost/version.txt` (You have probably no local Webserver^^)

But that should not cause any issues. I also removed this warning and show in the future:
`[WARN]: Can't connect to UpdateUrl "{URL}"... (Connection refused)`

Beside from that connection refused warning let me know if it works once you have the chance to test it =)

**Comment by Petschko** [comment]
I will also ask the user on the first run if they want to have the update check enabled, if not it never will create any connection, but currently it's not done.

**Comment by xpirad** [comment]
I see, nice feature!
Awesome! 👍
