### ISSUE TITLE
Doesnt work with OpenJDK

### ISSUE THREAD

**Issue by coolyves** [Petschko/Java-RPG-Maker-MV-Decrypter#20]
It worked until i switched to OpenJDK. Oracle Java is no longer free for some reason.
Can you make it work with OpenJDK as well?
I can start the application but when i load a directory it doesnt do anything.
When i test it with the cmd command this error message comes up:
Set Output-Dir to: "output"
Exception in thread "main" java.lang.NoClassDefFoundError: sun/dc/path/PathException
        at org.petschko.rpgmakermv.decrypt.App.main(App.java:41)
Caused by: java.lang.ClassNotFoundException: sun.dc.path.PathException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more

Thanks for the help
Greetings

**Comment by Petschko** [comment]
I think I remove the `sun.dc.path.PathException` (and replace it with something more helpful), it causes much more issues than it helps

**Comment by coolyves** [comment]
Thanks for the fast reply.
Have a nice Day

**Comment by Petschko** [comment]
I use my own PathException for it now! Please let me know if it works now with this Version:
[RPG_Maker_MV_Decrypter_jar_test.zip](https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/files/3144810/RPG_Maker_MV_Decrypter_jar_test.zip)

See code changes: https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/commit/4884279750d177c522be48eafeacfac7d2690f4f

**Comment by coolyves** [comment]
It works now. Thank your very much

**Comment by Petschko** [comment]
Thanks for testing it, I will put it out as release soon^^
