### ISSUE TITLE
Not working with OpenJDK 8+

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [Petschko/Java-RPG-Maker-MV-Decrypter#21]
OpenJDK missing `sun/dc/path/PathException`. This class probably exists only in Oracle version of Java.

```
$ java -debug -jar Java-RPG-Maker-MV-Decrypter.jar ./test ./output
RPG-Maker MV Decrypter - v0.1.3.1 (Hotfix) Alpha by Petschko | Command-Line Version
Set Project-Dir to: "./test"
Set Output-Dir to: "./output"
Exception in thread "main" java.lang.NoClassDefFoundError: sun/dc/path/PathException
	at org.petschko.rpgmakermv.decrypt.App.main(App.java:41)
Caused by: java.lang.ClassNotFoundException: sun.dc.path.PathException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 1 more
```

OS: Ubuntu Linux 16.04 amd64
Java:
```
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

**Comment by sergey-dryabzhinsky** [comment]
Tested with Oracle JDK 8 - working as expected.

**Comment by Petschko** [comment]
Yes that is true due to the sun Path-Exception. Its replaced it in the dev-branch, but im unsure if I work more on this project or rewrite it maybe

See:
https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/commit/4884279750d177c522be48eafeacfac7d2690f4f

**Comment by Petschko** [comment]
Duplicate: https://github.com/Petschko/Java-RPG-Maker-MV-Decrypter/issues/20

**Comment by Petschko** [comment]
I did a release of the version including the fix
