### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/jsoup/Jsoup

### ISSUE THREAD

**Issue by trannguyenhan** [Petschko/Java-RPG-Maker-MV-Decrypter#22]
I use Jsoup, i add jsoup to project but it error. i use Ubuntu OS
Exception in thread "main" java.lang.NoClassDefFoundError: org/jsoup/Jsoup
	at helloworld.HelloWorld.main(HelloWorld.java:12)
Caused by: java.lang.ClassNotFoundException: org.jsoup.Jsoup
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
pl help me? thank you so much!

**Comment by Petschko** [comment]
Hey you're sure you posted to the right Project?
