### ISSUE TITLE
Exception java.lang.NoClassDefFoundError on Ubuntu 16.04.4

### ISSUE THREAD

**Issue by xpirad** [Petschko/Java-RPG-Maker-MV-Decrypter#6]
I've installed openjdk 1.8.0_131

When i run the start.sh,following exception occurred:

Exception in thread "main" java.lang.NoClassDefFoundError: sun/dc/path/PathException
	at org.petschko.rpgmakermv.decrypt.App.main(App.java:37)
Caused by: java.lang.ClassNotFoundException: sun.dc.path.PathException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

This is really great tool i wish i could use it. Can you tell me how to solve this issue?

**Comment by Petschko** [comment]
I will have a look if I'm at home using Linux-Mint, if I get the same error...

If I need more information eg if I can't redo the error please help me to fix it, by providing informations..

But it should work normaly with Linux-Systems, so I have a look at it. If you need to decrypt files immediately, you can still use my Web-Decrypter until we figured out why this happens.

See: https://github.com/Petschko/RPG-Maker-MV-Decrypter


Thanks so far for creating this issue =)

**Comment by xpirad** [comment]
Thank you,Petschko.
I think i just found out how to solve this.
It seems to be related to some sun class which is not included in the openjdk by default.
After i switch to oracle jdk,it works like a charm!
Really nice tool you made,helped a lot!!

**Comment by Petschko** [comment]
Should not be an issue anymore since I got rid of the Oracle-Exception...
